--CREATE DATABASE ConSoleGame
--DROP DATABASE ConSoleGame
USE ConSoleGame


CREATE TABLE Category
(
  CategoryID  INT IDENTITY(1,1) NOT NULL,
  CategoryName  NVARCHAR(100) NOT NULL,
  PRIMARY KEY (CategoryID)
);

CREATE TABLE Account
(
  AccID INT IDENTITY(1,1) NOT NULL,
  FullName NVARCHAR(100), 
  UserName NVARCHAR(100) NOT NULL, 
  Email CHAR(300) NOT NULL,
  Password CHAR(64) NOT NULL,
  Role VARCHAR(50) NOT NULL,
  Birthday DATE ,
  Address NVARCHAR(300) ,
  Country NVARCHAR(100) ,
  PhoneNumber CHAR(11) ,
  Wallet MONEY,
  PRIMARY KEY (AccID)
);


CREATE TABLE Employee
(
  EmpID INT IDENTITY(1,1) NOT NULL,
  Position NVARCHAR(50) NOT NULL,
  AccID INT NOT NULL,
  FOREIGN KEY (AccID) REFERENCES Account(AccID),
  PRIMARY KEY (EmpID)
);


CREATE TABLE Product
(
  ProID INT IDENTITY(1,1) NOT NULL,
  ProName NVARCHAR(100) NOT NULL,
  Price MONEY NOT NULL,
  Discount FLOAT NOT NULL,
  Amount INT NOT NULL,
  CategoryID INT NOT NULL,
  Description NVARCHAR(4000) NOT NULL,
  PRIMARY KEY (ProID),
  FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID),
  
);


CREATE TABLE Orders
(
  OrdID INT IDENTITY(1,1) NOT NULL,
  RequiredDate DATE NOT NULL,
  ShippedDate DATE NOT NULL,
  ShipAdress NVARCHAR(300) NOT NULL,
  AccID INT NOT NULL,
  EmpID INT DEFAULT 0,
  [Status] NVARCHAR(100) NOT NULL,
  Total MONEY NOT NULL,
  FOREIGN KEY (AccID) REFERENCES Account(AccID),
  FOREIGN KEY (EmpID) REFERENCES Employee(EmpID),
  PRIMARY KEY (OrdID)
);

CREATE TABLE OrderDetail
(
  Quantity INT NOT NULL,
  Price MONEY NOT NULL,
  OrderDate DATE NOT NULL,
  OrdID INT NOT NULL,
  ProID INT NOT NULL,
  FOREIGN KEY (OrdID) REFERENCES Orders(OrdID),
  FOREIGN KEY (ProID) REFERENCES Product(ProID)
);